openapi: 3.1.0
info:
  title: Connect BCA
  version: 1.0.0
  description: API for generate payment using QR code
servers:
  - url: https://connect-bca.fly.dev/api/v1.0
    description: Staging server
tags:
  - name: QRIS
    description: Generate QR code for payment address
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ResponseQR:
      type: object
      properties:
        qrImage:
          type: string
        expiresAt:
          type: number
    ResponseVerifyQR:
      type: object
      oneOf:
        - properties:
            beneficiaryName:
              type: string
            beneficiaryAccountNumber:
              type: string
            remark:
              type: string
            expiresAt:
              type: number
          required:
            - beneficiary
            - remark
            - expiresAt
        - properties:
            sourceName:
              type: string
            sourceAccountNumber:
              type: string
            beneficiaryName:
              type: string
            beneficiaryAccountNumber:
              type: string
            amount:
              type: object
              properties:
                value:
                  type: number
                currency:
                  type: string
            remark:
              type: string
            expiresAt:
              type: number
          required:
            - source
            - beneficiary
            - amount
            - remark
            - expiresAt
paths:
  /qr/qr-transfer:
    get:
      summary: Generate QR Transfer
      tags:
        - QR Code
      security:
        - BearerAuth: []
      parameters:
        - name: mode
          in: query
          required: false
          schema:
            type: string
            enum: [bright, dark]
          description: Default mode is bright
        - name: option
          in: query
          required: false
          schema:
            type: string
            enum: [qr, url]
          description: Default option is qr
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseQR'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Error

  /qr/qr-pay:
    post:
      summary: Generate QR Payment
      tags:
        - QR Code
      security:
        - BearerAuth: []
      parameters:
        - name: mode
          in: query
          required: false
          schema:
            type: string
            enum: [bright, dark]
          description: Default mode is bright
        - name: option
          in: query
          required: false
          schema:
            type: string
            enum: [qr, url]
          description: Default option is qr
        - name: X-PIN-TOKEN
          in: header
          required: true
          schema:
            type: string
          description: PIN token required for authentication
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: object
                  properties:
                    value:
                      type: number
                    currency:
                      type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseQR'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Error
  /qr/qr-verify:
    post:
      summary: Verify QR Payload
      tags:
        - QR Code
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseVerifyQR'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Error